micronaut:
  application:
    name: musicman

jpa:
  default:
    entity-scan:
      packages: 'com.example'

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: 'acraft'
    password: ''

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
      async: true
